# cd = continuous deployment -> automation after the code got merged
name: cd

on:
  push:
    branch: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Building app
        run: ./scripts/buildprod.sh
